# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: 5
  username: postgres
  password: postgres
  host: db

development:
  <<: *default
  database: development

test:
  <<: *default
  database: test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
